CREATE TABLE IF NOT EXISTS consumo (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FECHA_CORTE VARCHAR(10),
  UNIDAD_NEGOCIO VARCHAR(100),
  PERIODO VARCHAR(10),
  TARIFA VARCHAR(10),
  FECHA_VENCIMIENTO VARCHAR(10),
  FECHA_EMISION VARCHAR(10),
  IMPORTE DECIMAL(20, 2),
  CONSUMO DECIMAL(20, 2)
);

LOAD DATA INFILE '/docker-entrypoint-initdb.d/datos_abiertos_consumohdna_202301_1kk.csv'
INTO TABLE consumo
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(FECHA_CORTE, UNIDAD_NEGOCIO, PERIODO, TARIFA, FECHA_VENCIMIENTO, FECHA_EMISION, IMPORTE, CONSUMO);