version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: hidrandina_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    command: --secure-file-priv=/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  web:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"

volumes:
  mysql_data:
